# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plean
email: plean0702@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you'll be able to read my most (not really) recent (not really either) writeups (if I fell like writing).
baseurl: ""
url: "https://plean.github.io/" # the base hostname & protocol for your site
twitter_username: plean702
github_username:  plean
theme: jekyll-theme-slate

# Build settings
markdown: kramdown
